version: '3'

services:
  puppeteer:
    image: buildkite/puppeteer
    volumes:
      - "./puppeteer:/puppeteer"
    networks:
      - pdfgen

  frontend:
    build: build/node
    image: pdfgen/node
    volumes:
      - "./frontend:/src"
    ports:
      - "127.0.0.1:8082:8082"
    networks:
      - pdfgen
    
networks:
  pdfgen:
    external: true